P_ZONE_NOTICE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('accounts/', include('apps.accountapp.urls')),
    path('parkscore/', include('apps.parkscore.urls')),
    path('parkarea/', include('apps.parkarea.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/urls.py
from django.urls import path
from apps.home.views import *

app_name = "home"

urlpatterns = [
    path('', index, name="home"),
    path("error1/", noGPS, name="nogps"),
    path("error2/", notGangNam, name="notgangnam"),
    path("angle/", angle, name="angle")
]

apps/parkarea/urls.py
from django.urls import path
from apps.parkarea.views import *

app_name = "parkarea"

urlpatterns = [
	path('parkmap/', parkmap, name="parkmap"),
]

apps/parkscore/urls.py
from django.urls import path
from apps.parkscore.views import *

app_name = "parkscore"

urlpatterns = [
	path('score/', score, name="score"),
	path('update/', update, name="update"),
	# path('photo/',forbidden_location,name="photo")
]

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.shortcuts import render
from apps.utils import connectDB

def index(request):
    if request.user.is_authenticated:
       sql = f"SELECT av_score FROM score WHERE username = '{request.user.username}'"
       row = connectDB(sql)
       if row:
           print(row)
           context = {"av_score": int(row[0][0])}
           return render(request, 'home.html', context)
       else:
           sql=f"INSERT INTO `score` (`username`, `av_score`) VALUES ('{request.user.username}', '50');"
           connectDB(sql, foo=True)
           sql = f"SELECT av_score FROM score WHERE username = '{request.user.username}'"
           row = connectDB(sql)
           print(row)
           context = {"av_score": int(row[0][0])}
           return render(request, 'home.html', context)
    else:
        context={}
        return render(request, 'home.html', context)


def noGPS(request):
    context = {}
    return render(request, "nogps.html", context)


def notGangNam(request):
    context = {}
    return render(request, "notgangnam.html", context)


def angle(request):
    context = {}
    return render(request, "angle.html", context)

apps/home/templates/angle.html
{% extends 'base.html' %}
{% load static %}
{% block title %}error{% endblock title %}
{% block content %}
<section class="page-section">
    <div class="container">
            <div class="d-flex justify-content-center">
                <div class="card" style="width: 40%; border: none;">
                    <img class="card-img-top img-responsive p-2" src="{% static 'images/warning.png' %}" id="warningImage" alt="warningImage" style="width: 100%">
                </div>
            </div>
            <div class="card bg-primary text-white text-center p-3 m-3" style="border: none;">
                <h3>개인형 이동장치가 넘어져 있습니다</h3>
            </div>
        </div>
</section>
{% endblock content %}

apps/home/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}홈{% endblock title %}
{% block content %}
<section class="page-section">
    <div class="container">
        {% if not user.is_authenticated %}
        <div class="d-flex justify-content-center">
            <div class="card text-center" style="width: 80%; border: none;">
                <h3>서비스 이용 시<br>로그인 해주시기 바랍니다</h3>
            </div>
        </div>

        {% else %}
        <div class="d-flex justify-content-center">
            <div class="card text-center border-primary m-4 px-2 py-3" style="width: 100%;">
                <div class="row align-items-center justify-content-center mb-3">
                    <div class="col-7">
                        <h3>{{ request.user.username }}님</h3><h5>주차 매너 점수</h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="progress">
                    <div class="progress-bar" id="userProgressBar" role="progressbar" style="width: {{av_score}}%" aria-valuenow="{{av_score}}" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                    </div>
                    <div class="col-4">
                        <span>{{av_score}}/100P</span>
                    </div>
                </div>
            </div>
        </div>


        {% endif %}
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

        <div class="d-flex justify-content-center">
            <form method="POST" action="{% url 'parkscore:score' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="lat" id="lat1">
                <input type="hidden" name="long" id="long1">
                <input type="file" accept="image/*;capture=camera" name="Camera"  id="Camera" style="display: none;" required>
                <button type="button" class="btn btn-primary m-3" id="scoreButton">
                    <img src="{% static 'images/electric-scooter.png' %}" class="img-responsive" style="width: 60%">
                    <p style="font-size: 1rem;">반납 확인</p>
                </button>
                <div class="row justify-content-center align-items-center">
                    <div class="col-6">
                        <button type="submit" class="btn btn-secondary"  style="display: none;" id="submitButton">전송</button>
                    </div>
                </div>
            </form>
            <form action="{% url 'parkarea:parkmap'  %}" method="GET" >
                <input type="hidden" name="lat" id="lat2">
                <input type="hidden" name="long" id="long2">
                <button type="submit" class="btn btn-primary m-3" id="areaButton">
                    <img src="{% static 'images/parking.png' %}" class="img-responsive" style="width: 60%">
                    <p style="font-size: 1rem;">주차 구역</p>
                </button>
            </form>
        </div>
    </div>
</section>

<script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.5.0/dialog-polyfill.js" charset="utf-8"></script>
<script type="text/javascript">
    function success(position) {
        const latitude  = position.coords.latitude;
        const longitude = position.coords.longitude;

        document.getElementById("lat1").value = latitude;
        document.getElementById("long1").value = longitude;
        document.getElementById("lat2").value = latitude;
        document.getElementById("long2").value = longitude;

    }
    function error(position) {
            //HTTPS가 아니거나 위치수집 동의를 안 할 경우
            alert("위치수집 동의를 해주세요")
        }

    if(!navigator.geolocation) {
        //Geolocation API를 지원하지 않는 브라우저일 경우
        alert(" 현 브라우저가 위치수집을 지원하지 않습니다.\n 다른 브라우저를 이용해주세요 ")

        } else {
        //Geolocation API를 지원하는 브라우저일 경우

        var optn = {enableHighAccuracy : true, timeout : 30000, maximumage: 0};
        function geolocation(){
                navigator.geolocation.getCurrentPosition(success, error,optn);
            }
        }

    function showResult() {
        let score = "{{ av_score }}";
        // 1. score에 따른 이미지
        if (score > 66) {
            $("#userProgressBar").addClass("bg-success");
        } else if (score > 33) {
            $("#userProgressBar").addClass("bg-warning");
        } else {
            $("#userProgressBar").addClass("bg-danger");
        }
    }

    $(document).ready(function () {
        geolocation();
        showResult();
    });

    $(document).on("click", "#scoreButton", function() {
        $("#Camera").click();
        $("#submitButton").css("display", "inline-block");
    });

</script>


{% endblock content%}

apps/home/templates/nogps.html
{% extends 'base.html' %}
{% load static %}
{% block title %}error{% endblock title %}
{% block content %}
<section class="page-section">
    <div class="container">
            <div class="d-flex justify-content-center">
                <div class="card" style="width: 40%; border: none;">
                    <img class="card-img-top img-responsive p-2" src="{% static 'images/warning.png' %}" id="warningImage" alt="warningImage" style="width: 100%">
                </div>
            </div>
            <div class="card bg-primary text-white text-center p-3 m-3" style="border: none;">
                <h3>GPS를 확인하세요</h3>
            </div>
        </div>
</section>
{% endblock content %}

apps/home/templates/notgangnam.html
{% extends 'base.html' %}
{% load static %}
{% block title %}error{% endblock title %}
{% block content %}
<section class="page-section">
    <div class="container">
            <div class="d-flex justify-content-center">
                <div class="card" style="width: 40%; border: none;">
                    <img class="card-img-top img-responsive p-2" src="{% static 'images/warning.png' %}" id="warningImage" alt="warningImage" style="width: 100%">
                </div>
            </div>
            <div class="card bg-primary text-white text-center p-3 m-3" style="border: none;">
                <h3>서비스 지역이 아닙니다</h3>
            </div>
        </div>
</section>
{% endblock content %}