P_ZONE_NOTICE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('accounts/', include('apps.accountapp.urls')),
    path('parkscore/', include('apps.parkscore.urls')),
    path('parkarea/', include('apps.parkarea.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import AccountCreateView
# AccountDetailView, AccountUpdateView, AccountDeleteView,

app_name="accountapp"

urlpatterns = [
path("login/",LoginView.as_view(template_name='accountapp/login.html'),name="login"),
path("logout/",LogoutView.as_view(),name="logout"),
path("create/", AccountCreateView.as_view(), name="create"),
# path('detail/<int:pk>',AccountDetailView.as_view(),name='detail'),
# path('update/<int:pk>',AccountUpdateView.as_view(),name='update'),
# path('delete/<int:pk>',AccountDeleteView.as_view(),name='delete')

]

apps/home/urls.py
from django.urls import path
from apps.home.views import *

app_name = "home"

urlpatterns = [
    path('', index, name="home"),
    path("error1/", noGPS, name="nogps"),
    path("error2/", notGangNam, name="notgangnam"),
    path("angle/", angle, name="angle")
]

templates/includes/footer.html
{% load static %}
<style>
    span.footer-icon {
        color: var(-bs-primary);
        font-size: 2rem;
    }
</style>
<nav class="navbar bg-white fixed-bottom" style="box-shadow: 0 -2px 2px -2px var(--bs-primary);">
    <div class="container position-relative" style="justify-content: space-evenly;">

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'accountapp:create' %}" style="color: #abc2e8">회원가입</a></li>
                <li class="nav-item"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'accountapp:login' %}" style="color: #abc2e8">로그인</a></li>
            </ul>
        </div>
        {% if not user.is_authenticated %}
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="footer-icon" style="color: var(--bs-primary)"><i class="fa-solid fa-right-to-bracket"></i></span>
        </button>
        {% else %}
        <a href="{% url 'accountapp:logout' %}">
            <span class="footer-icon"><i class="fa-solid fa-right-from-bracket"></i></span>
        </a>
        {% endif %}

        <a href="{% url 'home:home' %}">
            <span class="footer-icon"><i class="fa-solid fa-house"></i></span>
        </a>

        <a href="{% url 'home:home' %}">
            <span class="footer-icon"><i class="fa-solid fa-clipboard-question"></i></span>
        </a>
    </div>
</nav>

templates/includes/navigation.html
{% load static %}
<nav class="navbar bg-white fixed-top" style="box-shadow: 0 2px 2px -2px var(--bs-primary);">
    <div class="container position-relative" style="text-align: center; ">
        <a href="{% url 'home:home' %}">
            <img class="navbar-brand" src="{% static 'images/logo.png' %}" style="width: 30%">
        </a>
    </div>
</nav>