P_ZONE_NOTICE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('accounts/', include('apps.accountapp.urls')),
    path('parkscore/', include('apps.parkscore.urls')),
    path('parkarea/', include('apps.parkarea.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import AccountCreateView
# AccountDetailView, AccountUpdateView, AccountDeleteView,

app_name="accountapp"

urlpatterns = [
path("login/",LoginView.as_view(template_name='accountapp/login.html'),name="login"),
path("logout/",LogoutView.as_view(),name="logout"),
path("create/", AccountCreateView.as_view(), name="create"),
# path('detail/<int:pk>',AccountDetailView.as_view(),name='detail'),
# path('update/<int:pk>',AccountUpdateView.as_view(),name='update'),
# path('delete/<int:pk>',AccountDeleteView.as_view(),name='delete')

]

apps/parkscore/urls.py
from django.urls import path
from apps.parkscore.views import *

app_name = "parkscore"

urlpatterns = [
	path('score/', score, name="score"),
	path('update/', update, name="update"),
	# path('photo/',forbidden_location,name="photo")
]

apps/accountapp/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.

# class Score(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='Score')
#     message = rate = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(100.0)])
#

apps/accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

apps/accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView

from apps.accountapp.decorators import account_ownership_required
# from articleapp.models import Article
from apps.utils import connectDB


has_ownership=[account_ownership_required,login_required]



class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("home:home")
    template_name = 'accountapp/create.html'


# class AccountDetailView(DetailView,MultipleObjectMixin):
#     model = User
#     context_object_name = "target_user"
#     template_name = 'accountapp/detail.html'
#     paginate_by = 25
#
#     def get_context_data(self, **kwargs):
#         object_list = Article.objects.filter(writer=self.get_object())
#         return super(AccountDetailView, self).get_context_data(object_list=object_list,**kwargs)
#
# @method_decorator(has_ownership,'get')
# @method_decorator(has_ownership,'post')
# class AccountUpdateView(UpdateView):
#     model = User
#     form_class = AccountUpdateForm
#     context_object_name = "target_user"
#     success_url = reverse_lazy("home:home")
#     template_name = 'accountapp/update.html'
#
# @method_decorator(has_ownership,'get')
# @method_decorator(has_ownership,'post')
# class AccountDeleteView(DeleteView,):
#     model = User
#     success_url = reverse_lazy('accountapp:login')
#     context_object_name = "target_user"
#     template_name= 'accountapp/delete.html'
#

apps/accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align:center; max-width: 500px; margin:4rem auto">
  <div class=" mb-4">
    <h4>SignUp</h4>
  </div>
<form action="{% url 'accountapp:create' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="보내기">
</div>
{% endblock %}

apps/accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}


{% block content %}
<div style="text-align:center; max-width: 500px; margin:4rem auto">
  <div class=" mb-4">
    <h4>Quit</h4>
  </div>
<form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" value="삭제">
</form>
  </div>
{% endblock %}

apps/accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

  <div>
    <div class="pinteresting_500px_div">
      <p>
        {{target_user.date_joined}}
      </p>

      {% if target_user.profile %}
      <img src="{{ target_user.profile.image.url }}"
           style="height: 8rem; width: 8rem; border-radius: 10rem; margin-bottom: 2rem;
      object-fit:cover; " alt="">
      <h2 style="font-family:'NanumSquareB'">
        {{target_user.profile.nickname}}
        {% if target_user == user%}
        <a  class="material-icons"
            style="box-shadow:0 0 4px #ccc; padding:.4rem; border-radius:10rem"
                href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
        edit
        </a>
        {% endif %}
      </h2>
      <h5 style="margin-bottom:3rem;">
      {{ target_user.profile.message }}
      </h5>

      {% else %}
      {% if target_user == user%}
      <a href="{% url 'profileapp:create' %}">
      <h2 style="font-family:'NanumSquareB'">
        Create Profile
      </h2>
      </a>
      {% else %}
      <h4>
        닉네임 미설정
      </h4>
      {% endif %}
      {% endif %}

      {% if target_user.profile %}
      <a  class="material-icons"
            style="box-shadow:0 0 4px #ccc; padding:.4rem; border-radius:10rem"
                href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
        settings
        </a>
      <a  class="material-icons"
            style="box-shadow:0 0 4px #fcc; padding:.4rem; border-radius:10rem"
                href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
        cancel
        </a>
      {% endif %}



    </div>

  </div>
  <div>
    {% include 'snippets/list_fragment.html' with article_list=object_list %}
  </div>

{% endblock %}

apps/accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .testing{
        background-color:white;
        height:3rem;
        width:3rem;
        margin:1rem;

        }
    </style>
    <div style=" border-radius:1rem; margin: 2rem; text-align:center">
    <h1 style="font-family:'lobster',cursive">
        HELLO_WORLD_LIST
    </h1>
        <form action="/account/hello_world/" method="POST">
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>
        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
        <h1>
                {{hello_world.text}}
        </h1>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

apps/accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align:center; max-width: 500px; margin:4rem auto">
    <div >
        <h6>LOGIN</h6>
    </div>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>

{% endblock %}

apps/accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align:center; max-width: 500px; margin:4rem auto">
  <div class=" mb-4">
    <h4>Change</h4>
  </div>
<form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="보내기">
</form>
  </div>
{% endblock %}