P_ZONE_NOTICE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('accounts/', include('apps.accountapp.urls')),
    path('parkscore/', include('apps.parkscore.urls')),
    path('parkarea/', include('apps.parkarea.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/parkscore/urls.py
from django.urls import path
from apps.parkscore.views import *

app_name = "parkscore"

urlpatterns = [
	path('score/', score, name="score"),
	path('update/', update, name="update"),
	# path('photo/',forbidden_location,name="photo")
]

apps/parkscore/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator

# Create your models here.

# class support(models.Model):
#     writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     writeDT = models.DateTimeField(auto_now_add=True)
#     title = models.TextField()
#     question = models.TextField()
#     answer = models.TextField(null=True)
#     answered = models.IntegerField(choices=[(1, "y"), (0, "n")])

apps/parkscore/views.py
import json
import requests
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator

from haversine import haversine
from datetime import datetime

from apps.home.views import index
# from apps.parkscore.decorators import account_ownership_required
from apps.utils import connectDB, whether_gangnam


@login_required
def score(request):
    # Request Post일때
    if request.method == 'POST':
        try:
            long = float(request.POST.get('long'))
            lat = float(request.POST.get('lat'))
        except:
            return redirect("home:nogps")

        img = request.FILES['Camera']

        # 0. 강남구인지 확인
        whether, dongCode = whether_gangnam(lat, long)
        if whether:
            print(dongCode)
        else:
            return redirect("home:notgangnam")
        # dong_list = [row[0] for row in connectDB("SELECT dongcode FROM dong")]
        # API = "https://apis.openapi.sk.com/tmap/geo/reversegeocoding?version=1"
        # payload = {"appKey": "l7xx0ffb87c22bdb45ae8facaeeb7958ad36", "lon": long, "lat": lat}  # appkey secret 설정 필요
        # res = requests.get(API, params=payload)
        # dongCode = int(json.loads(res.text)["addressInfo"]["legalDongCode"][5:8])
        # if dongCode not in dong_list:
        #     return redirect("home:notgangnam")
        # else:
        #     print(dongCode)
        # 강남구가 아니면 다른 페이지로 보내는 작업 추가


        # 1. image
        url = "http://test2-model-svc:8000/file/store/"
        upload = {'file': img}
        image_result = requests.post(url, files=upload).json()  # kickboard, image_distance, uri
        kickboard = image_result["kickboard"]
        image_distance = image_result["image_distance"]
        # kickboard = True
        # image_distance = {"sidewalk": .3, "crosswalk": .2, "braille_block": 1.5, "bike_lane": .5}


        # 2. GPS
        sql = f"""SELECT UNIQUE c.type
                  FROM cautionzone c"""
        gps_distance = {key[0]: [100] for key in connectDB(sql)}

        criteria = 100
        marker_list = []
        # gps_class_list = []
        sql = f"""SELECT c.type, c.name, c.latitude, c.longitude
                  FROM cautionzone c
                  WHERE c.dongcode={dongCode}"""
        for row in connectDB(sql):
            latitude, longitude = float(row[2]), float(row[3])
            distance = haversine((lat, long), (latitude, longitude), unit="m")
            if distance < criteria:
                gps_distance[row[0]].append(distance)
                marker_list.append({"name": row[1], "latitude": latitude, "longitude": longitude})
                # gps_class_list.append(row[0])
        # gps_score = (20 - sum(Counter(gps_class_list).values())) / 5


        # 3. 기울기 sensor
        sensor_score = dict()

        slope_sensor_id = "ea2c64"
        sql = f"""SELECT i.time, i.inc
                  FROM inclination i
                  WHERE i.sen_id='{slope_sensor_id}'
                  ORDER BY i.`time` DESC LIMIT 1"""

        # now = datetime.utcnow()
        sensor_data = connectDB(sql)[0]
        print(sensor_data)
        time_diff = datetime.utcnow() - datetime.strptime(sensor_data[0], "%Y-%m-%d %H:%M:%S")

        if time_diff.seconds < 10:
            sensor_score["angle"] = 0
        else:
            sensor_score["angle"] = 1
        print(time_diff.seconds)


        # 4. final score
        cautions = {"kickboard": 1, "sensor": 1, "image": [], "gps": []}

        weights_dict = {"sidewalk": 5, "crosswalk": 17.6, "braille_block": 8.3, "bike_lane": 4.1,  ## 0 ~ 1.5
                        "bus": 8, "taxi": 8, "subway": 6.6, "fire": 0.1, "children": 1.4}  # 0 ~ 100
        message_dict = {"sidewalk": "보도블럭 중앙", "crosswalk": "횡단보도", "braille_block": "점자블럭", "bike_lane": "자전거도로",
                        "bus": "버스정류장", "taxi": "택시승강장", "subway": "지하철역", "fire": "지상소화전"}

        score = 100

        if kickboard == False:
            score = 0
            cautions["kickboard"] = 0
        elif sensor_score["angle"] == 0:
            score = 0
            cautions["angle"] = 0
        else:
            for key, value in image_distance.items():
                if value < 1.5:
                    temp_score = weights_dict[key] * (1.5 - value) * 20 / 3
                    score = score - temp_score
                    cautions["image"].append(message_dict[key])
            for key, value in gps_distance.items():
                min_value = min(value)
                if min_value < 100:
                    temp_score = weights_dict[key] * (100 - min_value) / 10
                    score = score - temp_score
                    cautions["gps"].append(message_dict[key])

        if score < 0:
            score = 0
        round_score = int(score)


        context = {
            "score": round_score,
            "cautions": cautions,
            "uri": image_result["uri"],
            "lat": lat,
            "long": long,
            "markerList": marker_list,
        }

        return render(request, 'score.html', context)


    ## request method가 Get일때
    else:
        return redirect('home:home')


@login_required
def update(request):
    # 3. 기울기 sensor
    slope_sensor_id = "ea2c64"
    sql = f"""SELECT i.time, i.inc
                      FROM inclination i
                      WHERE i.sen_id='{slope_sensor_id}'
                      ORDER BY i.`time` DESC LIMIT 1"""

    # now = datetime.utcnow()
    sensor_data = connectDB(sql)[0]
    time_diff = datetime.utcnow() - datetime.strptime(sensor_data[0], "%Y-%m-%d %H:%M:%S")

    if time_diff.seconds < 10:
        return redirect("home:angle")
    else:
        sql = f"SELECT av_score FROM score WHERE username = '{request.user.username}'"
        row = connectDB(sql)
        user_score = float(row[0][0])
        round_score = float(request.GET.get('score'))
        gap = (user_score - round_score) / 20
        update_score = round(user_score - gap, 0)

        sql = f"UPDATE `score` SET `av_score`='{update_score}' WHERE  `username`='{request.user.username}';"
        connectDB(sql, foo=True)

        return redirect('home:home')

apps/parkscore/templates/score.html
{% extends 'base.html' %}
{% load static %}
{% block title %}주차 점수{% endblock title %}
{% block content %}
<section class="page-section">
    <div class="container">
        <div class="d-flex justify-content-center">
            <div class="card" style="width: 40%; border: none;">
                <img class="card-img-top img-responsive p-2" src="" id="scoreImage" alt="scoreImage" style="width: 100%">
                <div class="card-body">
                    <h5 class="card-title text-center scoreText">{{ score }}점</h5>
                </div>
            </div>
        </div>

        <div class="card bg-primary text-white p-3" id="resultText" style="border: none;"></div>

        <!-- Image Modal -->
        <div class="modal fade" id="resultImage" tabindex="-1" aria-labelledby="resultImageModal" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="resultImageModalTitle">주차 이미지</h5>
                        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="ratio ratio-1x1">
                            <img class="img-responsive img-rounded" src="{{ uri }}" alt="resultImage" style="margin: auto;">
                        </div>
                        <div class="mt-3">
                            <ul style="list-style-type: disc;" id="resultImageList"></ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- GPS Modal -->
        <div class="modal fade" id="resultGPS" tabindex="-1" aria-labelledby="resultGPS" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="resultGPSTitle">주차 위치</h5>
                        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="ratio ratio-4x3">
                            <div id="map_div" style="width: 100%;"></div>
                        </div>
                        <div class="mt-3">
                            <ul style="list-style-type: disc;" id="resultGPSList"></ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- 반납 버튼 -->
        <div style="text-align: center;">
            <form action="{% url 'parkscore:update' %}" method="get">
                {% csrf_token %}
                <input type="hidden" name="score" value="{{score}}">
                <input type="submit" class="btn btn-secondary rounded-pill col-3 mt-12 submit-button m-3" value="반납">
            </form>
        </div>
    </div>

</section>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey=l7xx0ffb87c22bdb45ae8facaeeb7958ad36"></script>
<script type="text/javascript">
    function makeTmap() {
        var map;
        var marker;
        var lat = {{ lat }};
        var long = {{ long }};
        var markerList = {{ markerList|safe }};

        // 1. 지도 그리기
        map = new Tmapv2.Map("map_div",
            {
                center: new Tmapv2.LatLng(lat, long),
                width: "100%",
                zoom: 16,
                zoomControl: true,
                scrollwheel: true
            }
        );

        // 2. 현 위치 마커
        marker = new Tmapv2.Marker(
            {
                position: new Tmapv2.LatLng(lat, long),
                icon: "{% static 'images/here.png' %}",
                iconSize: new Tmapv2.Size(30, 30),
                map: map
            }
        );

        // 3. 주차 금지 구역 마커
        $.each(markerList, function(idx, item) {
            marker = new Tmapv2.Marker(
                {
                    position: new Tmapv2.LatLng(item.latitude, item.longitude),
                    icon: "{% static 'images/remove.png' %}",
                    iconSize: new Tmapv2.Size(20, 20),
                    map: map
                }
            );
        });
    }

    function removeTmap() {
        $("#map_div").empty();
    }

    function hideModal() {
        // modal 버튼 숨기기
        $(".modal-button").css("display", "none");
        $(".submit-button").css("display", "none");
    }

    function showResult() {
        var score = {{ score }};
        var cautionList = {{ cautions|safe }};
        var imageList = cautionList.image;
        var gpsList = cautionList.gps;


        // 1. score에 따른 이미지
        if (score > 66) {
            $("#scoreImage").prop("src", "{% static 'images/good.png'%}");
        } else if (score > 33) {
            $("#scoreImage").prop("src", "{% static 'images/neutral.png'%}");
        } else {
            $("#scoreImage").prop("src", "{% static 'images/bad.png'%}");
        }
        console.log(cautionList.kickboard);


        if (cautionList.kickboard == 0) {
            hideModal();
            $("#resultText").append("사진에 개인형 이동장치를 확인할 수 없습니다");
        } else if (cautionList.angle == 0) {
            hideModal();
            $("#resultText").append("개인형 이동장치가 넘어져 있습니다");
        }

        if (imageList.length > 0) {
            $("#resultText").append("<h4><span><i class='fa-solid fa-circle-check'></i></span>    이미지 속 주차금지구역</h4>");
            $("#resultText").append("<div class='row'><div class='col-9' id='resultImageText'></div><div class='col-3' id='resultImageButton'></div>");
            $.each(imageList, function(idx, item) {
                $("#resultImageText").append("<li>"+item+"</li>");
            });
            $("#resultImageButton").append('<button class="btn btn-secondary m-3 modal-button" type="button" data-bs-toggle="modal" data-bs-target="#resultImage"><span><i class="fa-solid fa-image"></i></span></button>')
        }

        if (gpsList.length > 0) {
            if ($("#resultText > h4").length) {
                $("#resultText").append("<hr>");
            }
            $("#resultText").append("<h4><span><i class='fa-solid fa-circle-check'></i><span>    현 위치 인근 주차금지구역</h4>");
            $("#resultText").append("<div class='row'><div class='col-9' id='resultGPSText'></div><div class='col-3' id='resultGPSButton'></div>");
            $.each(gpsList, function(idx, item) {
                $("#resultGPSText").append("<li>"+item+"</li>");
            });
            $("#resultGPSButton").append('<button class="btn btn-secondary m-3 modal-button" type="button" data-bs-toggle="modal" data-bs-target="#resultGPS"><span><i class="fa-solid fa-map-location-dot"></i></span></button>')
        }
    }

    $(document).ready(function() {showResult()});
    $("#resultGPS").on("shown.bs.modal", function() {makeTmap()});
    $("#resultGPS").on("hidden.bs.modal", function() {removeTmap()});
</script>
{% endblock content %}